### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by UI233** [UI233/RayTracer#1]
#### Base
- [x] Main Rendering Procedure（buggy） **UI**
- [x] Basic Camera **UI**
- [x] Simple Startified Sampler **UI**
- [ ] Basic Material **Lu Jian**
- [x] Primitives and Model **Logos**

#### More
- [x] Light Source(untested)
- [x] Texture
- [ ] ~More Efficent Sampler and Reconstructor~
- [ ] Advanced Material(More Complex Reflection Model)

#### Optional
- [ ] A Dynamical Demo Scene
